package org.yu.projectcx.network.signaling;

/**
 * Enumeration of WebRTC signaling message types for connection negotiation via Hosted/Cloud Signaling Server.
 */
public enum SignalingType {
    /**
     * Peer registers its identity (peerId) with the hosted signaling server.
     */
    REGISTER,

    /**
     * Server broadcasts or returns list of online peers currently connected.
     */
    PEER_LIST,

    /**
     * Server broadcasts notification when a new peer joins the signaling room.
     */
    PEER_JOINED,

    /**
     * Server broadcasts notification when a peer disconnects.
     */
    PEER_LEFT,

    /**
     * SDP (Session Description Protocol) connection offer initiated by Peer A to Peer B.
     */
    OFFER,

    /**
     * SDP connection answer generated by Peer B in response to an Offer.
     */
    ANSWER,

    /**
     * Interactive Connectivity Establishment (ICE) candidate containing IP/Port routing candidates.
     */
    ICE_CANDIDATE,

    /**
     * Periodic ping/pong signaling frame to maintain NAT hole punching and keep-alive.
     */
    HEARTBEAT,

    /**
     * P2P Chat message payload transmitted over direct signaling channel as instant fallback/channel.
     */
    CHAT_MESSAGE,

    /**
     * Explicit disconnect/teardown signal.
     */
    BYE,

    /**
     * Connection request sent from Peer A to Peer B.
     */
    CONNECT_REQUEST,

    /**
     * Connection accepted signal sent from Peer B to Peer A.
     */
    CONNECT_ACCEPT,

    /**
     * Connection rejected/declined signal sent from Peer B to Peer A.
     */
    CONNECT_REJECT,

    /**
     * Query requesting a peer's currently connected active peers.
     */
    PEER_NETWORK_QUERY,

    /**
     * Response returning a peer's currently connected active peers.
     */
    PEER_NETWORK_RESPONSE,

    /**
     * Request to join a peer's active group connection.
     */
    GROUP_JOIN_REQUEST,

    /**
     * Acceptance of a group join request.
     */
    GROUP_JOIN_ACCEPT,

    /**
     * Introduction of a new peer to other members of an existing group connection.
     */
    GROUP_INTRODUCE
}
